# .github/workflows/regenerate-changelog.yml

name: Regenerate GitHub Release

on:
  # 允许你从 GitHub Actions 页面手动触发此工作流
  workflow_dispatch:
    inputs:
      # 定义一个输入框，让你在触发时填入需要修复的 Git 标签
      tagName:
        description: 'The git tag to regenerate the changelog for (e.g., v1.0.1)'
        required: true
        type: string

# 权限
permissions:
  contents: write


jobs:
  regenerate:
    runs-on: ubuntu-latest
    steps:
      # 检出代码
      # 确保检出的是你手动输入的那个特定的标签
      - name: Checkout specific tag
        uses: actions/checkout@v4
        with:
          # 这一步是关键，它会获取所有的提交历史，changelogithub 需要完整的历史记录
          fetch-depth: 0
          # 检出你通过输入框传入的标签
          ref: ${{ github.event.inputs.tagName }}

      # 安装 Node.js 和 pnpm
      # 如果你的 changelog 生成依赖于项目中的某些开发依赖，则需要此步骤
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.15.1

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.13.0'
          cache: 'pnpm'
      


      # 重新生成 Changelog
      # 这一步会为当前检出的标签（即你输入的标签）创建或更新 GitHub Release
      - name: Generate changelog
        run: pnpm dlx changelogithub --no-group
        env:
          # GITHUB_TOKEN 是必须的，用于授权给 GitHub API 来创建 Release
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
